# Use a specific Python version
FROM python:3.12.6-slim as base

# Prevents Python from writing pyc files and keeps Python from buffering stdout and stderr
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory
WORKDIR /app

# Create a non-privileged user
ARG UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    appuser

# Install Node.js and npm
RUN apt-get update && apt-get install -y nodejs npm

# Copy package.json and package-lock.json
COPY package*.json ./

# Debug: List contents of /app
RUN ls -la /app

# Install Node.js dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Install Python dependencies
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements.txt

# Build the React app (if needed)
RUN npm run build
RUN npm cache clean --force

# Switch to the non-privileged user
USER appuser

# Expose the port that the application listens on
EXPOSE 8000

# Run the application
CMD ["npm", "start"]